spring:
  datasource:
    url: jdbc:hsqldb:file:D:/CourseSpring/hsqldb/data/student-db
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        show_sql: false
        # Hibernate ddl auto (create, create-drop, validate, update)
        hibernate.hbm2ddl.auto: create

  # logging
logging:
  level:
    org:
      iproduct:
        spring:
          restmvc: DEBUG
